# server confs
PORT: "8080"

# db confs
DB_NAME: "db"
DB_USER: "user"
DB_HOST: "postgres"
DB_PORT: "5432"
DB_PASS: "password"

# redis confs
REDIS_HOST: "redis"
REDIS_PORT: "6379"
REDIS_PASSWORD: "redispassword"
REDIS_DB: 0

# jwt confs
ACCESS_TTL: 15
REFRESH_TTL: 10
ACTIVE_SESSIONS: 5

# ws confs
WRITE_WAIT: 15s
PONG_WAIT: 90s
PING_PERIOD: 83s
MAX_MESSAGE_SIZE: 512

# kafka confs
KAFKA_BROKERS: 
  - "kafka:9092"
KAFKA_TOPIC_MESSAGES: messenger-messages
KAFKA_TOPIC_DLQ: messenger-dlq
KAFKA_GROUP_ID: messenger-group
# producer kafka
KAFKA_MAX_RETRY: 3
KAFKA_BATCH_SIZE: 100
KAFKA_LINGER_MS: 10
KAFKA_REQUIRED_ACKS: 1
KAFKA_COMPRESSION_TYPE: snappy
# consumer kafka
KAFKA_SESSION_TIMEOUT: 30
KAFKA_AUTO_OFFSET_RESET: earliest
KAFKA_MIN_BYTES: 10240
KAFKA_MAX_BYTES: 10485760
KAFKA_MAX_WAIT_TIME: 250
# timeouts kafka
KAFKA_WRITE_TIMEOUT: 10
KAFKA_READ_TIMEOUT: 10
# kafka max msg count in queue in read
KAFKA_MAX_QUEUE_SIZE: 10