# server confs
PORT: "8080"

# db confs
DB_NAME: "db"
DB_USER: "sibhelly"
DB_HOST: "localhost"
DB_PORT: "5432"
DB_PASS: "password"

# jwt confs
ACCESS_TTL: 15
REFRESH_TTL: 10
ACTIVE_SESSIONS: 5

# ws confs
WRITE_WAIT: 15s
PONG_WAIT: 90s
PING_PERIOD: 83s
MAX_MESSAGE_SIZE: 512